-- AlterTable
ALTER TABLE `brute` MODIFY `hp` INTEGER NOT NULL DEFAULT 10,
    MODIFY `force` INTEGER NOT NULL DEFAULT 1,
    MODIFY `endurance` INTEGER NOT NULL DEFAULT 1,
    MODIFY `agilite` INTEGER NOT NULL DEFAULT 1,
    MODIFY `currentxp` INTEGER NOT NULL DEFAULT 0,
    MODIFY `level` INTEGER NOT NULL DEFAULT 1,
    MODIFY `maxxp` INTEGER NOT NULL DEFAULT 10;
